# This is a basic workflow to help you get started with Actions

name: CI - Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Install server dependencies
      - name: Install server dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: server

      # Install web dependencies
      - name: Install web dependencies
        run: cd web && npm install --legacy-peer-deps
      
      # Run Component & API & UI & Tests
      - name: Run Component & API & UI & Tests
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: web
          install: false
          start: npm run start:ci
          wait-on: 'http://localhost:3000'
          
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: screenshots
          path: web/cypress/screenshots
     
      # Upload videos
      - name: Upload videos
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: videos
          path: web/cypress/videos
          
      # Merge mochawesome report
      - name: Merge mochawesome reports
        run: npm run report:merge
      
      # Generate mochawesome report
      - name: Generate mochawesome reports
        run: npm run report:mocha
      
      # Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          token: ${{ github.token }}
          branch: gh-pages
          folder: mochawesome-report

